services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: cloudapp
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d cloudapp"]
      interval: 3s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend/CloudApp.Api
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=cloudapp;Username=app;Password=app
    depends_on:
      db:
        condition: service_healthy
